[book]
authors = ["Viet Than"]
language = "en"
multilingual = false
src = "src"
title = "VietnamMUN Guide for Organizers, Chairs, and Delegates"

[output.html]
git-repository-url = "https://github.com/VietnamMUN/book-copy"
git-repository-icon = "building-un"
edit-url-template = "https://github.com/VietnamMUN/book-copy/edit/main/{path}"
# site-url = "/example-book/"
